language: perl
services:
  - redis-server
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
env:
  - "HARNESS_OPTIONS=j1 TEST_POD=1 REDIS_TEST_DATABASE=default"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage EV"
  - "cpanm -n --installdeps ."
notifications:
  email: false
